language: go

go:
    - 1.7

install:
    - go get github.com/golang/lint/golint

script:
    - go get -t -v ./...
    - go build
    - go fmt ./...
    - golint ./...
    - go vet ./...
    - go test -v -race ./...
